// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	GetAccount(ctx context.Context, id int64) (Account, error)
	GetAccountForUpdate(ctx context.Context, id int64) (Account, error)
	GetEntryByAccountID(ctx context.Context, accountID int64) ([]Entry, error)
	GetEntryByID(ctx context.Context, id int64) (Entry, error)
	GetTransferByFromAccountID(ctx context.Context, fromAccountID int64) ([]Transfer, error)
	GetTransferByID(ctx context.Context, id int64) (Transfer, error)
	GetTransferByToAccountID(ctx context.Context, toAccountID int64) ([]Transfer, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	ListTransfers(ctx context.Context, arg ListTransfersParams) ([]Transfer, error)
	UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (Account, error)
	UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) (Account, error)
}

var _ Querier = (*Queries)(nil)
